version: 2
updates:
  # npmパッケージの依存関係を管理
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00"
      timezone: "Asia/Tokyo"
    # PRの設定
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
    # Tailwind CSS関連パッケージを除外
    ignore:
      - dependency-name: "tailwindcss"
      - dependency-name: "postcss"
      - dependency-name: "autoprefixer"
    # React系のパッケージの更新はまとめて実施
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "major"
          - "minor"
          - "patch"
